name: Publish to Registry
on:
  push:
    branches:
      - master
    paths:
      - "**/Dockerfile"
      - ".github/workflows/deploy.yml"
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

env:
  DOCKER_USERNAME: tiryoh
  DOCKER_IMAGENAME: ros-desktop-vnc
  GIT_CONFIG_USER: Tiryoh@GitHubActions
  GIT_CONFIG_EMAIL: tiryoh@gmail.com

jobs:
  build-and-deploy:
    strategy:
      fail-fast: false
      matrix:
        ros-distro: [melodic, melodic-arm64, noetic, noetic-arm64]
        experimental: [false]
        include:
          - ros-distro: noetic-testing
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - name: Build docker image
        env:
          DOCKER_TAGNAME: ${{ matrix.ros-distro }}
        run: |
          cd $DOCKER_TAGNAME && docker build -t $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME .

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to docker.io
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish docker image
        env:
          DOCKER_TAGNAME: ${{ matrix.ros-distro }}
        id: docker
        run: |
          TIMESTAMP=$(date '+%Y%m%dT%H%M')
          # ghcr.io
          docker tag $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME ghcr.io/$DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME
          docker tag $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME ghcr.io/$DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME-$TIMESTAMP
          docker push ghcr.io/$DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME
          docker push ghcr.io/$DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME-$TIMESTAMP
          # docker.io
          docker push $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME
          docker tag $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME-$TIMESTAMP
          docker push $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME-$TIMESTAMP
          echo ::set-output name=timestamp::$TIMESTAMP
          echo ::set-output name=digest::$(docker inspect --format='{{index .RepoDigests 0}}' $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME-$TIMESTAMP)

      - name: Publish docker image as latest
        if: contains(matrix.ros-distro, 'noetic') == true
        env:
          DOCKER_TAGNAME: ${{ matrix.ros-distro }}
        run: |
          docker tag $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAGNAME $DOCKER_USERNAME/$DOCKER_IMAGENAME:latest
          docker push $DOCKER_USERNAME/$DOCKER_IMAGENAME:latest

      - name: Get Current Job Log URL
        id: jobs
        uses: Tiryoh/gha-jobid-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: build-and-deploy (${{ matrix.ros-distro }})

      - name: Update GitHub wiki
        env:
          DOCKER_TAGNAME: ${{ matrix.ros-distro }}
          DOCKER_SNAPSHOT: ${{ matrix.ros-distro }}-${{ steps.docker.outputs.timestamp }}
          DOCKER_DIGEST_RAW: ${{ steps.docker.outputs.digest }}
        run: |
          DOCKER_DIGEST=$(echo $DOCKER_DIGEST_RAW | sed -E 's/.*@sha256:(.*)/sha256-\1/g')
          DOCKER_DIGEST_SHORT=$(echo $DOCKER_DIGEST | sed -E 's/.*([0-9a-z]{12})[0-9a-z]{52}$/\1/g')
          DOCKER_IMAGE_HISTORY_URL=$(echo https://hub.docker.com/layers/${DOCKER_USERNAME}/${DOCKER_IMAGENAME}/${DOCKER_TAGNAME}/images/${DOCKER_DIGEST})
          DOCKER_SNAPSHOT_IMAGE_HISTORY_URL=$(echo https://hub.docker.com/layers/${DOCKER_USERNAME}/${DOCKER_IMAGENAME}/${DOCKER_SNAPSHOT}/images/${DOCKER_DIGEST})
          git clone --depth=1 https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.wiki.git wiki
          cd wiki
          LINE=$(grep -n "add $DOCKER_TAGNAME msg after this line" ${{ matrix.ros-distro }}.md | cut -d ":" -f 1)
          head -n $LINE ${{ matrix.ros-distro }}.md > tmp.md
          echo "* \`${DOCKER_DIGEST_SHORT}\`" | tee -a tmp.md
          echo "    * uploaded on $(date --iso-8601="minutes")" | tee -a tmp.md
          echo "        * ${{ steps.jobs.outputs.html_url }}" | tee -a tmp.md
          echo "    * snapshot" | tee -a tmp.md
          echo "        * [\`${DOCKER_SNAPSHOT}\`](${DOCKER_SNAPSHOT_IMAGE_HISTORY_URL})" | tee -a tmp.md
          tail -n +$(( $LINE+1 )) ${{ matrix.ros-distro }}.md >> tmp.md
          mv tmp.md ${{ matrix.ros-distro }}.md
          git config --local user.email "${GIT_CONFIG_EMAIL}"
          git config --local user.name "${GIT_CONFIG_USER}"
          git add ${{ matrix.ros-distro }}.md
          git commit -m "Update ${{ matrix.ros-distro }}.md"
          git fetch origin && git merge origin/master --no-edit && git push origin master
